language: node_js
before_install:
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz
  - tar xvfz git-lfs-linux-amd64-1.1.2.tar.gz
  - mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/
services: mongodb
sudo: false
node_js:
  - "4.1.1"
  - "4.2.5"
