---
version: "3"
services:
  mongo: 
    image: mongo
    volumes: 
      - "$HOME/.deepforge/data:/data/db"
  server: 
    environment: 
      - "MONGO_URI=mongodb://mongo:27017/deepforge"
      - "DEEPFORGE_HOST=https://dev.deepforge.org"
    image: deepforge/kitchen-sink:latest
    ports: 
      - "8888:8888"
    volumes: 
      - "$HOME/.deepforge/blob:/data/blob"
      - "${TOKEN_KEYS_DIR}:/deepforge/token_keys"
    depends_on:
      - mongo