---
version: "3"
services: 
  mongo: 
    image: mongo
    volumes: 
      - "$HOME/.deepforge/data:/data/db"
  server: 
    environment: 
      - "MONGO_URI=mongodb://mongo:27017/deepforge"
    image: tumesh/deepforge
    ports: 
      - "8888:8888"
    volumes: 
      - "$HOME/.deepforge/blob:/data/blob"
      - "../token_keys:/token_keys"
    depends_on:
      - mongo
