services:
  server:
    entrypoint: /.deployment/dev-entrypoint.sh
    volumes:
      - "$HOME/.deepforge/blob:/data/blob"
      - "${TOKEN_KEYS_DIR}:/token_keys"
      - "${DEEPFORGE_DEPLOYMENT_DIR}:/.deployment"
      - "${DEEPFORGE_DEPLOYMENT_DIR}/../config/components.json:/deepforge/config/components.json"

  server_stable:
    entrypoint: /.deployment/dev-entrypoint.sh
    environment:
      - "MONGO_URI=mongodb://mongo:27017/deepforge"
      - "DEEPFORGE_HOST=https://editor.deepforge.org"
      - "DEEPFORGE_PUBLIC_KEY=/token_keys/public_key"
      - "DEEPFORGE_PRIVATE_KEY=/token_keys/private_key"
    image: deepforge/kitchen-sink:stable
    ports:
      - "8889:8888"
    volumes:
      - "$HOME/.deepforge/blob:/data/blob"
      - "${TOKEN_KEYS_DIR}:/token_keys"
      - "${DEEPFORGE_DEPLOYMENT_DIR}:/.deployment"
      - "${DEEPFORGE_DEPLOYMENT_DIR}/../config/components.json:/deepforge/config/components.json"
    depends_on:
      - mongo
