name: Build Deepforge Dev Server

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tumesh/deepforge
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build:
    runs-on: ubuntu-latest

    steps:
    - name: deploy deepforge
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          echo "This is a test script" > fileout.txt