name: SSH Server Build Action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: deploy deepforge
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          echo "This is a test script" > fileout.txt