name: Push Deepforge Server(Latest) to Docker Hub and Deploy dev.deepforge.org

on:
  push:
    branches:
      - master
      - 1596-deployment-script

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish to docker hub (server)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: deepforge/server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"

      - name: Publish to docker hub (kitchen-sink)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: deepforge/kitchen-sink
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
          dockerfile: Dockerfile.kitchensink

      - name: Deploy (dev.deepforge.org)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            rf -rf deepforge && git clone https:git@github.com:deepforge-dev/deepforge && cd deepforge
            git checkout -b 1596-deployment-script origin/1596-deployment-script
            chmod +x ./.deployment/deploy-deepforge && ./.deployment/deploy-deepforge


