name: Push Deepforge Server(Latest) to Docker Hub and Deploy dev.deepforge.org

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Release Tags
        id: get_release_tags
        run: |
          echo "RELEASE_TAG=$(echo ${GITHUB_REF} | sed -E 's/.*v?([0-9]+)\.([0-9]+)\.([0-9]+)?/\1.\2.\3,\1.\2,\1/')" >> $GITHUB_ENV
          echo "TAG=stable" >> $GITHUB_ENV
        if: github.event_name == 'release'

      - name: Get Push Tags
        id: get_push_tags
        run: |
          echo "TAG=latest" >> $GITHUB_ENV
          echo "RELEASE_TAG=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV


      - name: Publish to docker hub (server)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: deepforge/server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "1908-pyls-integration"
          dockerfile: docker/Dockerfile

      - name: Publish to docker hub (kitchen-sink)
        uses: elgohr/Publish-Docker-Github-Action@master

        with:
          name: deepforge/kitchen-sink
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "1908-pyls-integration"
          dockerfile: docker/Dockerfile.kitchensink
          buildargs: "TAG=1908-pyls-integration"

      - name: Publish to docker hub (language-servers)
        uses: elgohr/Publish-Docker-Github-Action@master

        with:
          name: deepforge/language-servers
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          dockerfile: docker/Dockerfile.langservers


      - name: Deploy (dev.deepforge.org)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            rm -rf deepforge && git clone git@github.com:deepforge-dev/deepforge && cd deepforge && git checkout -b 1908-pyls-integration origin/1908-pyls-integration
            chmod +x ./.deployment/deploy-deepforge && ./.deployment/deploy-deepforge

      - name: Deploy (editor.deepforge.org)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            rm -rf deepforge-stable && git clone git@github.com:deepforge-dev/deepforge deepforge-stable && cd deepforge-stable
            git checkout -b stable $(git tag | tail -1)
            chmod +x ./.deployment/deploy-deepforge && ./.deployment/deploy-deepforge stable
        if: github.event_name == 'release'
