name: Push Deepforge Server(Latest) to Docker Hub and Deploy dev.deepforge.org

on:
  push:
    branches:
      - master
      - 1516-docker-release-action
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Release Tags
        id: get_version
        run: |
          echo "::set-env name=RELEASE_TAG_NAME::$(echo ${GITHUB_REF:10})"
          echo "::set-env name=DEFAULT_TAG_NAME::stable"
        if: github.event_name == 'release'

      - name: Get Push Tags
        id: get_release_tags
        run: |
          echo "::set-env name=DEFAULT_TAG_NAME::latest"
          echo "::set-env name=RELEASE_TAG_NAME::$(echo ${GITHUB_REF:11})"
        if: github.event_name == 'push'

      - name: Publish to docker hub (server)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: deepforge/server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ env.DEFAULT_TAG_NAME }},${{ env.RELEASE_TAG_NAME }}"

      - name: Publish to docker hub (kitchen-sink)
        uses: elgohr/Publish-Docker-Github-Action@master

        with:
          name: deepforge/kitchen-sink
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ env.DEFAULT_TAG_NAME }},${{ env.RELEASE_TAG_NAME }}"
          dockerfile: Dockerfile.kitchensink
          buildargs: "${{ env.DEFAULT_TAG_NAME }}"


      - name: Deploy (dev.deepforge.org)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            rm -rf deepforge && git clone git@github.com:deepforge-dev/deepforge && cd deepforge
            chmod +x ./.deployment/deploy-deepforge && ./.deployment/deploy-deepforge
        if: github.event_name == 'push'

      - name: Deploy (editor.deepforge.org)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            rm -rf deepforge-stable && git clone git@github.com:deepforge-dev/deepforge-stable && cd deepforge-stable
            chmod +x ./.deployment/deploy-deepforge && ./.deployment/deploy-deepforge stable
        if: github.event_name == 'release'
