name: Publish to NPM

on:
  push:
    branches:
      - 1612-npm-publish-action
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull Minio
        run: |
          docker pull minio/minio
          docker run -d -p 9000:9000 --name minio-test -e "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}" -e "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}" minio/minio server ./data
      - name: Install Conda
        run: |
          source utils/install-conda.sh



