name: Release Docker File Build

on:
  push:
    branches:
      - 1516-docker-release-action
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: git checkout 1516-docker-release-action
      - name: Publish to docker hub (Stable-Server)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: deepforge/server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "stable-demo"

      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: git checkout 1516-docker-release-action
      - name: Publish to docker hub (kitchen-sink-stable)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: deepforge/kitchen-sink
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "stable-demo"
          dockerfile: Dockerfile.kitchensink

      - name: Deploy (editor.deepforge.org)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            bash -ic deploy-deepforge stable
